### ISSUE TITLE
When creating a mqtt-connection with an auto mqtt-publish the message should be send when the connection is established

### ISSUE THREAD

**Issue by sandro-k** [mqttjs/mqtt-elements#13]
```
<mqtt-connection
    url="ws://iot.eclipse.org:80/ws"
    auto>
  <mqtt-publish topic="foo/bar" payload="this is easy" auto></mqtt-publish>
</mqtt-connection>
```

Minimal working example dose not automatically publish to "foo/bar" when the the connection is established. Probably [`_propertiesChanged`](https://github.com/mqttjs/mqtt-elements/blob/81246731248c72ff93c2c5222b35b2266e7ced5a/mqtt-publish.html#L111) is not run when `this._parentConnection` is set via its parent.

**Comment by mcollina** [comment]
You can just call `client.publish()` even before a `'connect'` event in MQTT.js, the publish will be queued up and sent as the connection is established (for the first time).

**Comment by sandro-k** [comment]
I know.. but the `mqtt-publish` element will not have any knowledge about which client it belongs too until set by the parent `mqtt-connection` . Even the `mqtt-connection` might get the client injected via its mqtt-connection#client property and then will delegate it down to the `mqtt-publish` element. Anyway just wanted to document this and create a fix and test for it.
